[package]
name = "rust-websocket"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
base64 = "0.22.1"
sha1 = "0.10.6"
rand = "0.8.5"

[dependencies.uuid]
version = "1.10.0"
features = ["v4"]
